apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld-default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld-default
  template:
    metadata:
      labels:
        app: aks-helloworld-default
    spec:
      serviceAccountName: nginx
      containers:
      - name: aks-helloworld-default
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-default  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld-default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-anyuid
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-allow-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-anyuid
subjects:
- kind: ServiceAccount
  name: nginx